# frozen_string_literal: true

require "ddsketch/proto/ddsketch_pb"

module DDSketch
  # Namespace for protobuf object generated by `google-protobuf`
  # @!visibility private
  module Proto
    module_function

    def serialize_sketch(sketch)
      DDSketch.new(
        mapping: serialize_key_mapping(sketch.mapping),
        positiveValues: serialize_store(sketch.store),
        negativeValues: serialize_store(sketch.negative_store),
        zeroCount: sketch.zero_count
      )
    end

    def serialize_store(store)
      Store.new(
        contiguousBinCounts: store.bins,
        contiguousBinIndexOffset: store.offset
      )
    end

    def serialize_key_mapping(mapping)
      IndexMapping.new(
        gamma: mapping.relative_accuracy,
        indexOffset: mapping.offset,
        interpolation: serialize_interpolation(mapping)
      )
    end

    def serialize_interpolation(mapping)
      {
        linear: IndexMapping::Interpolation::LINEAR,
        cubic: IndexMapping::Interpolation::CUBIC
      }.fetch(mapping.interpolation) { IndexMapping::Interpolation::NONE }
    end
  end
end
